import { Roboto } from '@next/font/google'
import type { NextComponentType, NextPageContext } from 'next'
import Head from 'next/head'
import { ReactElement } from 'react'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

interface Props {
    children: ReactElement
}

const Layout: NextComponentType<NextPageContext, {}, Props> = ({
    children,
}) => {
    return (
        <>
            <Head>
                <title>Quoc & Lan</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className={`min-h-screen w-full bg-cover bg-fixed bg-center ${roboto.className}`}
            >
                {children}
            </main>
        </>
    )
}

export default Layout
