import Clock from '@/components/Clock'
import Timeline from '@/components/Timeline'
import { Roboto } from '@next/font/google'
import Head from 'next/head'

const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})

export default function Home() {
    return (
        <>
            <Head>
                <title>Quoc & Lan</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`w-full ${roboto.className}`}>
                <section id="clock" className="bg-cover bg-fixed bg-center">
                    <Clock />
                </section>
                <section className="bg-black p-12">
                    <Timeline />
                </section>
            </main>
        </>
    )
}
