import Card from '@/components/card'
import Clock from '@/components/clock'
import { cardDetails } from '@/utils/cardDetails'
import { Roboto } from '@next/font/google'
import Head from 'next/head'
import { Mousewheel, Pagination } from 'swiper'
import 'swiper/css'
import 'swiper/css/pagination'
import { Swiper, SwiperSlide } from 'swiper/react'

const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})

export default function Home() {
    return (
        <>
            <Head>
                <title>Quoc & Lan</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className={`h-screen w-full bg-cover bg-fixed bg-center ${roboto.className}`}
            >
                <section className="flex h-screen w-screen flex-col items-center justify-center bg-black/50">
                    <Swiper
                        direction={'vertical'}
                        slidesPerView={1}
                        centeredSlides={true}
                        mousewheel={true}
                        pagination={{
                            clickable: true,
                        }}
                        loop={true}
                        modules={[Mousewheel, Pagination]}
                        className="h-full w-full"
                    >
                        <SwiperSlide>
                            <Clock />
                        </SwiperSlide>
                        {cardDetails.map((detail) => {
                            return (
                                <SwiperSlide key={detail.name}>
                                    <Card detail={detail} />
                                </SwiperSlide>
                            )
                        })}
                    </Swiper>
                </section>
            </main>
        </>
    )
}
